[2024-11-23T15:41:12.551+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T15:41:12.569+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: interpark_to_s3.extract scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T15:41:12.581+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: interpark_to_s3.extract scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T15:41:12.582+0000] {taskinstance.py:2866} INFO - Starting attempt 10 of 10
[2024-11-23T15:41:12.598+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): extract> on 2024-11-22 00:00:00+00:00
[2024-11-23T15:41:12.605+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=587) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T15:41:12.606+0000] {standard_task_runner.py:72} INFO - Started process 588 to run task
[2024-11-23T15:41:12.607+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'interpark_to_s3', 'extract', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp2tkbycbz']
[2024-11-23T15:41:12.609+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask extract
[2024-11-23T15:41:12.663+0000] {task_command.py:467} INFO - Running <TaskInstance: interpark_to_s3.extract scheduled__2024-11-22T00:00:00+00:00 [running]> on host 37998fa7166f
[2024-11-23T15:41:12.763+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='interpark_to_s3' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T15:41:12.765+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T15:41:12.780+0000] {baseoperator.py:416} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2024-11-23T15:41:12.781+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvcufxnpxs --python=python
[2024-11-23T15:41:12.783+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T15:41:13.618+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 198ms
[2024-11-23T15:41:13.618+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvcufxnpxs, clear=False, no_vcs_ignore=False, global=False)
[2024-11-23T15:41:13.619+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-23T15:41:13.619+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2024-11-23T15:41:13.619+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-23T15:41:13.652+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvcufxnpxs/bin/pip install -r /tmp/venvcufxnpxs/requirements.txt
[2024-11-23T15:41:13.653+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T15:41:15.083+0000] {process_utils.py:194} INFO - Collecting git+https://github.com/hahahellooo/interpark.git@0.3/new_crawling (from -r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:15.084+0000] {process_utils.py:194} INFO -   Cloning https://github.com/hahahellooo/interpark.git (to revision 0.3/new_crawling) to /tmp/pip-req-build-vdrej8mz
[2024-11-23T15:41:15.087+0000] {process_utils.py:194} INFO -   Running command git clone --filter=blob:none --quiet https://github.com/hahahellooo/interpark.git /tmp/pip-req-build-vdrej8mz
[2024-11-23T15:41:16.510+0000] {process_utils.py:194} INFO -   Running command git checkout -b 0.3/new_crawling --track origin/0.3/new_crawling
[2024-11-23T15:41:17.118+0000] {process_utils.py:194} INFO -   Switched to a new branch '0.3/new_crawling'
[2024-11-23T15:41:17.119+0000] {process_utils.py:194} INFO -   branch '0.3/new_crawling' set up to track 'origin/0.3/new_crawling'.
[2024-11-23T15:41:17.119+0000] {process_utils.py:194} INFO -   Resolved https://github.com/hahahellooo/interpark.git to commit d2ab75a632be9f578ac04be0e85d884befd10f87
[2024-11-23T15:41:17.127+0000] {process_utils.py:194} INFO -   Installing build dependencies: started
[2024-11-23T15:41:19.587+0000] {process_utils.py:194} INFO -   Installing build dependencies: finished with status 'done'
[2024-11-23T15:41:19.588+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: started
[2024-11-23T15:41:20.402+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: finished with status 'done'
[2024-11-23T15:41:20.404+0000] {process_utils.py:194} INFO -   Preparing metadata (pyproject.toml): started
[2024-11-23T15:41:21.196+0000] {process_utils.py:194} INFO -   Preparing metadata (pyproject.toml): finished with status 'done'
[2024-11-23T15:41:21.326+0000] {process_utils.py:194} INFO - Collecting selenium>=4.26.1 (from interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.328+0000] {process_utils.py:194} INFO -   Using cached selenium-4.26.1-py3-none-any.whl.metadata (7.1 kB)
[2024-11-23T15:41:21.364+0000] {process_utils.py:194} INFO - Collecting beautifulsoup4>=4.12.3 (from interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.366+0000] {process_utils.py:194} INFO -   Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
[2024-11-23T15:41:21.403+0000] {process_utils.py:194} INFO - Collecting soupsieve>1.2 (from beautifulsoup4>=4.12.3->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.405+0000] {process_utils.py:194} INFO -   Using cached soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
[2024-11-23T15:41:21.479+0000] {process_utils.py:194} INFO - Collecting urllib3<3,>=1.26 (from urllib3[socks]<3,>=1.26->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.481+0000] {process_utils.py:194} INFO -   Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
[2024-11-23T15:41:21.518+0000] {process_utils.py:194} INFO - Collecting trio~=0.17 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.519+0000] {process_utils.py:194} INFO -   Using cached trio-0.27.0-py3-none-any.whl.metadata (8.6 kB)
[2024-11-23T15:41:21.550+0000] {process_utils.py:194} INFO - Collecting trio-websocket~=0.9 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.551+0000] {process_utils.py:194} INFO -   Using cached trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
[2024-11-23T15:41:21.591+0000] {process_utils.py:194} INFO - Collecting certifi>=2021.10.8 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.593+0000] {process_utils.py:194} INFO -   Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
[2024-11-23T15:41:21.633+0000] {process_utils.py:194} INFO - Collecting typing_extensions~=4.9 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.635+0000] {process_utils.py:194} INFO -   Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
[2024-11-23T15:41:21.676+0000] {process_utils.py:194} INFO - Collecting websocket-client~=1.8 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.678+0000] {process_utils.py:194} INFO -   Using cached websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
[2024-11-23T15:41:21.715+0000] {process_utils.py:194} INFO - Collecting attrs>=23.2.0 (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.716+0000] {process_utils.py:194} INFO -   Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
[2024-11-23T15:41:21.759+0000] {process_utils.py:194} INFO - Collecting sortedcontainers (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.762+0000] {process_utils.py:194} INFO -   Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
[2024-11-23T15:41:21.796+0000] {process_utils.py:194} INFO - Collecting idna (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.797+0000] {process_utils.py:194} INFO -   Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
[2024-11-23T15:41:21.823+0000] {process_utils.py:194} INFO - Collecting outcome (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.825+0000] {process_utils.py:194} INFO -   Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
[2024-11-23T15:41:21.852+0000] {process_utils.py:194} INFO - Collecting sniffio>=1.3.0 (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.854+0000] {process_utils.py:194} INFO -   Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
[2024-11-23T15:41:21.887+0000] {process_utils.py:194} INFO - Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.889+0000] {process_utils.py:194} INFO -   Using cached wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
[2024-11-23T15:41:21.921+0000] {process_utils.py:194} INFO - Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3,>=1.26->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.922+0000] {process_utils.py:194} INFO -   Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
[2024-11-23T15:41:21.953+0000] {process_utils.py:194} INFO - Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvcufxnpxs/requirements.txt (line 1))
[2024-11-23T15:41:21.954+0000] {process_utils.py:194} INFO -   Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
[2024-11-23T15:41:21.964+0000] {process_utils.py:194} INFO - Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
[2024-11-23T15:41:21.965+0000] {process_utils.py:194} INFO - Using cached selenium-4.26.1-py3-none-any.whl (9.7 MB)
[2024-11-23T15:41:21.972+0000] {process_utils.py:194} INFO - Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
[2024-11-23T15:41:21.974+0000] {process_utils.py:194} INFO - Using cached soupsieve-2.6-py3-none-any.whl (36 kB)
[2024-11-23T15:41:21.975+0000] {process_utils.py:194} INFO - Using cached trio-0.27.0-py3-none-any.whl (481 kB)
[2024-11-23T15:41:21.976+0000] {process_utils.py:194} INFO - Using cached trio_websocket-0.11.1-py3-none-any.whl (17 kB)
[2024-11-23T15:41:21.977+0000] {process_utils.py:194} INFO - Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
[2024-11-23T15:41:21.978+0000] {process_utils.py:194} INFO - Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
[2024-11-23T15:41:21.979+0000] {process_utils.py:194} INFO - Using cached websocket_client-1.8.0-py3-none-any.whl (58 kB)
[2024-11-23T15:41:21.980+0000] {process_utils.py:194} INFO - Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
[2024-11-23T15:41:21.981+0000] {process_utils.py:194} INFO - Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
[2024-11-23T15:41:21.982+0000] {process_utils.py:194} INFO - Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
[2024-11-23T15:41:21.983+0000] {process_utils.py:194} INFO - Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
[2024-11-23T15:41:21.985+0000] {process_utils.py:194} INFO - Using cached idna-3.10-py3-none-any.whl (70 kB)
[2024-11-23T15:41:21.986+0000] {process_utils.py:194} INFO - Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
[2024-11-23T15:41:21.987+0000] {process_utils.py:194} INFO - Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
[2024-11-23T15:41:21.989+0000] {process_utils.py:194} INFO - Using cached h11-0.14.0-py3-none-any.whl (58 kB)
[2024-11-23T15:41:22.019+0000] {process_utils.py:194} INFO - Building wheels for collected packages: interpark
[2024-11-23T15:41:22.023+0000] {process_utils.py:194} INFO -   Building wheel for interpark (pyproject.toml): started
[2024-11-23T15:41:22.807+0000] {process_utils.py:194} INFO -   Building wheel for interpark (pyproject.toml): finished with status 'done'
[2024-11-23T15:41:22.808+0000] {process_utils.py:194} INFO -   Created wheel for interpark: filename=interpark-0.1.2-py3-none-any.whl size=17701 sha256=8010a986b4dec89a634bec60b7f755cd755c1d05017366d5771d0257dc01c104
[2024-11-23T15:41:22.808+0000] {process_utils.py:194} INFO -   Stored in directory: /tmp/pip-ephem-wheel-cache-2dyf6jor/wheels/3b/e3/3f/2198c53e48ab1c477124eda1522aad636d2590cc0e6349feda
[2024-11-23T15:41:22.810+0000] {process_utils.py:194} INFO - Successfully built interpark
[2024-11-23T15:41:22.842+0000] {process_utils.py:194} INFO - Installing collected packages: sortedcontainers, websocket-client, urllib3, typing_extensions, soupsieve, sniffio, pysocks, idna, h11, certifi, attrs, wsproto, outcome, beautifulsoup4, trio, trio-websocket, selenium, interpark
[2024-11-23T15:41:25.540+0000] {process_utils.py:194} INFO - Successfully installed attrs-24.2.0 beautifulsoup4-4.12.3 certifi-2024.8.30 h11-0.14.0 idna-3.10 interpark-0.1.2 outcome-1.3.0.post0 pysocks-1.7.1 selenium-4.26.1 sniffio-1.3.1 sortedcontainers-2.4.0 soupsieve-2.6 trio-0.27.0 trio-websocket-0.11.1 typing_extensions-4.12.2 urllib3-2.2.3 websocket-client-1.8.0 wsproto-1.2.0
[2024-11-23T15:41:25.898+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvcufxnpxs/bin/python /tmp/venv-callcn4m6arw/script.py /tmp/venv-callcn4m6arw/script.in /tmp/venv-callcn4m6arw/script.out /tmp/venv-callcn4m6arw/string_args.txt /tmp/venv-callcn4m6arw/termination.log
[2024-11-23T15:41:25.899+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T15:41:26.604+0000] {process_utils.py:194} INFO - The chromedriver version (114.0.5735.90) detected in PATH at /usr/local/bin/chromedriver might not be compatible with the detected chrome version (131.0.6778.85); currently, chromedriver 131.0.6778.85 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry
[2024-11-23T15:41:26.808+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2024-11-23T15:41:26.809+0000] {process_utils.py:194} INFO -   File "/tmp/venv-callcn4m6arw/script.py", line 48, in <module>
[2024-11-23T15:41:26.809+0000] {process_utils.py:194} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-23T15:41:26.809+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T15:41:26.810+0000] {process_utils.py:194} INFO -   File "/tmp/venv-callcn4m6arw/script.py", line 20, in get_data
[2024-11-23T15:41:26.810+0000] {process_utils.py:194} INFO -     get_data = extract_container_html()
[2024-11-23T15:41:26.810+0000] {process_utils.py:194} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T15:41:26.810+0000] {process_utils.py:194} INFO -   File "/tmp/venvcufxnpxs/lib/python3.12/site-packages/interpark/test.py", line 19, in extract_container_html
[2024-11-23T15:41:26.811+0000] {process_utils.py:194} INFO -     driver = webdriver.Chrome(options=chrome_options)
[2024-11-23T15:41:26.811+0000] {process_utils.py:194} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T15:41:26.811+0000] {process_utils.py:194} INFO -   File "/tmp/venvcufxnpxs/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
[2024-11-23T15:41:26.811+0000] {process_utils.py:194} INFO -     super().__init__(
[2024-11-23T15:41:26.812+0000] {process_utils.py:194} INFO -   File "/tmp/venvcufxnpxs/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
[2024-11-23T15:41:26.812+0000] {process_utils.py:194} INFO -     super().__init__(command_executor=executor, options=options)
[2024-11-23T15:41:26.813+0000] {process_utils.py:194} INFO -   File "/tmp/venvcufxnpxs/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
[2024-11-23T15:41:26.813+0000] {process_utils.py:194} INFO -     self.start_session(capabilities)
[2024-11-23T15:41:26.813+0000] {process_utils.py:194} INFO -   File "/tmp/venvcufxnpxs/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
[2024-11-23T15:41:26.813+0000] {process_utils.py:194} INFO -     response = self.execute(Command.NEW_SESSION, caps)["value"]
[2024-11-23T15:41:26.814+0000] {process_utils.py:194} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T15:41:26.814+0000] {process_utils.py:194} INFO -   File "/tmp/venvcufxnpxs/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
[2024-11-23T15:41:26.814+0000] {process_utils.py:194} INFO -     self.error_handler.check_response(response)
[2024-11-23T15:41:26.814+0000] {process_utils.py:194} INFO -   File "/tmp/venvcufxnpxs/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2024-11-23T15:41:26.815+0000] {process_utils.py:194} INFO -     raise exception_class(message, screen, stacktrace)
[2024-11-23T15:41:26.815+0000] {process_utils.py:194} INFO - selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
[2024-11-23T15:41:26.815+0000] {process_utils.py:194} INFO -   (unknown error: DevToolsActivePort file doesn't exist)
[2024-11-23T15:41:26.815+0000] {process_utils.py:194} INFO -   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2024-11-23T15:41:26.815+0000] {process_utils.py:194} INFO - Stacktrace:
[2024-11-23T15:41:26.816+0000] {process_utils.py:194} INFO - #0 0x559a90a694e3 <unknown>
[2024-11-23T15:41:26.816+0000] {process_utils.py:194} INFO - #1 0x559a90798c76 <unknown>
[2024-11-23T15:41:26.816+0000] {process_utils.py:194} INFO - #2 0x559a907c1d78 <unknown>
[2024-11-23T15:41:26.816+0000] {process_utils.py:194} INFO - #3 0x559a907be029 <unknown>
[2024-11-23T15:41:26.816+0000] {process_utils.py:194} INFO - #4 0x559a907fcccc <unknown>
[2024-11-23T15:41:26.816+0000] {process_utils.py:194} INFO - #5 0x559a907fc47f <unknown>
[2024-11-23T15:41:26.817+0000] {process_utils.py:194} INFO - #6 0x559a907f3de3 <unknown>
[2024-11-23T15:41:26.817+0000] {process_utils.py:194} INFO - #7 0x559a907c92dd <unknown>
[2024-11-23T15:41:26.817+0000] {process_utils.py:194} INFO - #8 0x559a907ca34e <unknown>
[2024-11-23T15:41:26.817+0000] {process_utils.py:194} INFO - #9 0x559a90a293e4 <unknown>
[2024-11-23T15:41:26.817+0000] {process_utils.py:194} INFO - #10 0x559a90a2d3d7 <unknown>
[2024-11-23T15:41:26.817+0000] {process_utils.py:194} INFO - #11 0x559a90a37b20 <unknown>
[2024-11-23T15:41:26.818+0000] {process_utils.py:194} INFO - #12 0x559a90a2e023 <unknown>
[2024-11-23T15:41:26.818+0000] {process_utils.py:194} INFO - #13 0x559a909fc1aa <unknown>
[2024-11-23T15:41:26.818+0000] {process_utils.py:194} INFO - #14 0x559a90a526b8 <unknown>
[2024-11-23T15:41:26.818+0000] {process_utils.py:194} INFO - #15 0x559a90a52847 <unknown>
[2024-11-23T15:41:26.818+0000] {process_utils.py:194} INFO - #16 0x559a90a62243 <unknown>
[2024-11-23T15:41:26.818+0000] {process_utils.py:194} INFO - #17 0x7fbe147a5144 <unknown>
[2024-11-23T15:41:26.819+0000] {process_utils.py:194} INFO - 
[2024-11-23T15:41:26.927+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559a90a694e3 <unknown>
#1 0x559a90798c76 <unknown>
#2 0x559a907c1d78 <unknown>
#3 0x559a907be029 <unknown>
#4 0x559a907fcccc <unknown>
#5 0x559a907fc47f <unknown>
#6 0x559a907f3de3 <unknown>
#7 0x559a907c92dd <unknown>
#8 0x559a907ca34e <unknown>
#9 0x559a90a293e4 <unknown>
#10 0x559a90a2d3d7 <unknown>
#11 0x559a90a37b20 <unknown>
#12 0x559a90a2e023 <unknown>
#13 0x559a909fc1aa <unknown>
#14 0x559a90a526b8 <unknown>
#15 0x559a90a52847 <unknown>
#16 0x559a90a62243 <unknown>
#17 0x7fbe147a5144 <unknown>

[2024-11-23T15:41:26.932+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=interpark_to_s3, task_id=extract, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T154112, end_date=20241123T154126
[2024-11-23T15:41:26.957+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T15:41:26.958+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task extract (Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559a90a694e3 <unknown>
#1 0x559a90798c76 <unknown>
#2 0x559a907c1d78 <unknown>
#3 0x559a907be029 <unknown>
#4 0x559a907fcccc <unknown>
#5 0x559a907fc47f <unknown>
#6 0x559a907f3de3 <unknown>
#7 0x559a907c92dd <unknown>
#8 0x559a907ca34e <unknown>
#9 0x559a90a293e4 <unknown>
#10 0x559a90a2d3d7 <unknown>
#11 0x559a90a37b20 <unknown>
#12 0x559a90a2e023 <unknown>
#13 0x559a909fc1aa <unknown>
#14 0x559a90a526b8 <unknown>
#15 0x559a90a52847 <unknown>
#16 0x559a90a62243 <unknown>
#17 0x7fbe147a5144 <unknown>
; 588)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559a90a694e3 <unknown>
#1 0x559a90798c76 <unknown>
#2 0x559a907c1d78 <unknown>
#3 0x559a907be029 <unknown>
#4 0x559a907fcccc <unknown>
#5 0x559a907fc47f <unknown>
#6 0x559a907f3de3 <unknown>
#7 0x559a907c92dd <unknown>
#8 0x559a907ca34e <unknown>
#9 0x559a90a293e4 <unknown>
#10 0x559a90a2d3d7 <unknown>
#11 0x559a90a37b20 <unknown>
#12 0x559a90a2e023 <unknown>
#13 0x559a909fc1aa <unknown>
#14 0x559a90a526b8 <unknown>
#15 0x559a90a52847 <unknown>
#16 0x559a90a62243 <unknown>
#17 0x7fbe147a5144 <unknown>

[2024-11-23T15:41:27.025+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T15:41:27.041+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T15:41:27.046+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
